# https://taskfile.dev

version: '3'

output: prefixed

includes:
  arduino: ./ArduinoTasks.yml

tasks:
  default:
    cmds:
      - task: build

  build:
    deps:
      - task: build-luddite

  build-luddite:
    cmds:
      - task: arduino:buildboard
        vars:
          KEYBOARD: 'luddite'
          KEYBOARDCONFIG: 'single'
          FQBNFOLDER: 'pca10056'
          CONTROLLERFOLDER: 'bluemicro840'
          KEYMAP: 'default'
          FQBN: 'community_nrf52:nrf52:pca10056'
